type: object
description: Reference to a benchmark in a collection or evaluation
allOf:
  - $ref: ./Ref.yaml
  - type: object
    required:
      - provider_id
    properties:
      provider_id:
        type: string
        description: Evaluation provider ID
      weight:
        type: number
        format: float
        minimum: 0
        maximum: 1
        description: Weight of this benchmark
      primary_score:
        $ref: ./PrimaryScore.yaml
      pass_criteria:
        $ref: ./PassCriteria.yaml
      parameters:
        type: object
        additionalProperties: true
        description: Benchmark-specific parameters
