type: object
description: Configuration for MLFlow experiment tracking.
properties:
  name:
    type: string
    description: >
      Experiment name for MLFlow tracking.

      If there is an `active` experiment with the same name, it will be reused.
      If there is no `active` experiment with the same name, a new experiment will be created.
    title: Name
  tags:
    type: array
    description: >
      Tags for the evaluation experiment.
    items:
      $ref: ./ExperimentTag.yaml
    maxItems: 20
    title: Tags
  artifact_location:
    type: string
    description: >
      Artifact location is the directory where the evaluation artifacts will be stored.
      If not provided, the default artifact location will be used by the MLFlow server.
    title: Artifact Location
required:
  - name
additionalProperties: false
title: Experiment Config
